app/src/main/res/values-de/strings.xml
Almost complete german translation, except of the `Dialog: KeepTrying GPS?`.
Updates #15.
=> Update #15, german translation.

app/src/main/res/values-pl/strings.xml
The name of the app is "Zmierzchy i Świty" which means "Dusks and Dawns"; direct translation "Czasy Słońca" (Suntimes - Times of the Sun) looks weird. Default location is Warsaw (capital city of Poland).
=> Polskie tłumaczenie/Polish translation

app/src/main/java/com/forrestguice/suntimeswidget/SuntimesActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesConfigActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidget.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidget1.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidget1Service.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidgetListActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/settings/AppSettings.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_headers.xml, app/src/main/res/xml/preference_headers_legacy.xml, app/src/main/res/xml/preference_locale.xml
adds language settings (#23) / override the system locale
=> add language settings

.gitignore, app/build.gradle, app/src/main/java/com/forrestguice/suntimeswidget/AboutDialog.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesUtils.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidgetListActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesCalculator.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesCalculatorFactory.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/ca/rmen/sunrisesunset/SunriseSunsetSuntimesCalculator.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/sunrisesunset_java/SunriseSunsetSuntimesCalculator.java, app/src/main/res/layout/layout_dialog_about.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml, build.gradle
new datasource ca.rmen.sunrisesunset
=> Datasource1

app/src/main/res/values-eo/strings.xml
In Esperanto family names are usually CAPITALIZED.
=> update strings (eo)

app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
I created this French translation. Hope it helps. Cheers,
J.
=> Added French translation

app/src/main/res/values-hu/strings.xml
=> Hungarian strings.xml

README.md, app/src/androidTest/java/com/forrestguice/suntimeswidget/SuntimesActivityTestBase.java, app/src/androidTest/java/com/forrestguice/suntimeswidget/SuntimesResTest.java, app/src/androidTest/java/com/forrestguice/suntimeswidget/SuntimesScreenshots.java, app/src/androidTest/java/com/forrestguice/suntimeswidget/TimeZoneDialogTest.java
automatic screenshot generation (for each supported locale)
=> screenshots

app/app.iml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es-rES/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
Merge branch with spanish and catalan translations.
Android Studio modified the app.iml file.
=> Es ca translation

app/src/main/res/values-pl/strings.xml
sorry for endless editions, I must pay higher attention to context of strings
=> Update strings.xml (pl)

app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
=> Update German localisation

CHANGELOG.md, app/src/main/java/com/forrestguice/suntimeswidget/MoonPhasesView.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesCalculatorFactory.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesData.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesEquinoxSolsticeData.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesEquinoxSolsticeDataset.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesMoonData.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesRiseSetDataset.java, app/src/main/res/values/strings.xml
fixes problems described in #198
=> calculator

CHANGELOG.md, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/notes/SuntimesNotes.java, app/src/main/java/com/forrestguice/suntimeswidget/settings/AppSettings.java, app/src/main/res/xml/preference_userinterface.xml
Adds options to toggle visibility of twilight times displayed by the app (hide fields).
=> Hidefields

app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml
updated Polish and Esperanto translations
=> ĝisdatigis polan kaj esperantan tradukojn

app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es-rES/strings.xml, app/src/main/res/values-eu/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Add Chinese translation

CHANGELOG.md, app/build.gradle
* fixes bug "'get location' does not honor the 'units of length' pref" (#290).
* improves the accuracy of the apparent solar time calculation (#291).
* updates translation to Basque (eu) (#294 by beriain)
=> release 0.10.2

CHANGELOG.md, app/build.gradle
* fixes crash when opening general settings (Esperanto) (#315).
* adds "rise/set order" help button to the widget configuration activity.
* misc. layout and icon changes (Widget List, About).
* updates translations to Polish (pl) and Esperanto (eo) (#317 by Verdulo).
* updates translations to Brazilian Portuguese (pt-br) (#319 by Neto Silva).
=> release 0.11.3

app/src/main/res/values-pt-rBR/strings.xml
Interface issue fixed and news words translated. I believe now it's 100%.
=> Brazilian Portuguese Translation reviewed

CHANGELOG.md, app/build.gradle
* fixes bug "NotificationService is always running" (#323, #324).
* fixes bug "AlarmClockActivity started multiple times" (#325, #324).
* removes the "location mode" selector from widget configuration (widgets only support "user-defined") (#10).
* updates translations to Brazilian Portuguese (pt-br) (#320 by Neto Silva).
=> release 0.11.4

app/src/main/java/com/forrestguice/suntimeswidget/SuntimesUtils.java, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml
Additional changes. I think writing style is better now.
=> Updated Spanish & Catalan translations.

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/48.txt
* updates translations to Spanish (es-es) and Catalan (ca) (#340, #343 by Raulvo).
=> release 0.11.7

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/50.txt
* fixes app crash when supplied with invalid data (bad URI, alarmID, or widgetID) ("Intent resolution bugs"; #353).
* updates translation to Brazilian Portuguese (pt-br) (#350 by Neto Silva).
=> release 0.11.9

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/51.txt
* fixes app layout issues for Brazilian Portuguese (pt-br) and Norwegian (nb) translations (#356).
* fixes bug "date dialog fails to respect timezone setting" (#358).
* fixes bug "note selection lost on orientation change" (#359).
* updates translation to Brazilian Portuguese (pt-br) (#357 by naoliv).
=> release 0.11.10

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/53.txt
* fixes app crash (moon phase alarms) (#365).
* updates translation to Norwegian (nb) (#366 by FTno).
* updates translations to Polish (pl) and Esperanto (eo) (#367 by Verdulo).
=> release 0.12.1

app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java
* allow alarms to be dismissed early (reschedule+1) (#387).
* adds "dismiss" button to the reminder notification (and reveals the notification for api21+).
* TIME_SET broadcast no longer triggers reschedule.
=> alarmclock

app/src/androidTest/java/com/forrestguice/suntimeswidget/themes/SuntimesThemeProviderTest.java, app/src/androidTest/java/com/forrestguice/suntimeswidget/themes/SuntimesThemeTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesConfigActivity0.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/CalculatorProvider.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/core/CalculatorProviderContract.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/SuntimesTheme.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/SuntimesThemeContract.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/SuntimesThemeProvider.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/SuntimesThemeXML.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/WidgetThemeConfigActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/WidgetThemeListActivity.java
* adds a ContentProvider (SuntimesThemeProvider) that provides access to user-defined themes.
* exports the ThemeList activity; permits access to third-party apps with the `suntimes.permission.READ_CALCULATOR` permission.
=> theme provider

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/61.txt
* fixes bug "Widget Title Substitution %lel uses meters only" (fixes #410).
* fixes NullPointerException when refreshing location (fixes #408).
=> release 0.12.9

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/62.txt
* fixes bug "solar time alarms are offset by several minutes" (fixes #414).
* updates translation to German (de) (#412 by xnumad).
=> release 0.12.10

app/src/main/java/com/forrestguice/suntimeswidget/LightMapDialog.java, app/src/main/res/layout/layout_dialog_objheight.xml, app/src/main/res/values/strings.xml
Adds "object height" popup slider to the sun position dialog; "Quick set" the object height to a value bewteen 0.01 and 30 meters. (#189)
=> object height popup

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/67.txt
* fixes crash in Manage Places when copying or editing places (fixes #443).
* adds an object height slider (shadow length) to sun position dialog (#189, #442).
* updates translation to Brazilian Portuguese (pt-br) (#441 by naoliv).
=> release 0.13.3

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/68.txt
* updates translation to Brazilian Portuguese (pt-br) (#450 by naoliv). 
* updates translation to Norwegian (nb) (#447 by FTno).
* updates translation to Polish and Esperanto (eo, pl) (#446 by Verdulo).
=> release 0.13.4

app/src/main/java/com/forrestguice/suntimeswidget/SuntimesConfigActivity0.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesUtils.java, app/src/main/java/com/forrestguice/suntimeswidget/TimeZoneDialog.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmClockItem.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesData.java, app/src/main/java/com/forrestguice/suntimeswidget/settings/WidgetSettings.java, app/src/main/java/com/forrestguice/suntimeswidget/settings/WidgetTimezones.java, app/src/main/res/layout/layout_settings_timezone0.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-eu/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
* renames "solar time" setting to "time standard"; adds "UTC".
* adds support for sidereal time (GMST, LMST) (#463) .
* misc time zone spinner layout tweaks.
=> sidereal time

app/src/main/res/values-nl/strings.xml
=> update Dutch translation

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/73.txt
* updates translation to Catalan (ca) and Spanish (es) (#478, #479 by gnusuari0).
* updates translation to Dutch (nl) (#486, #487 by Joppla).
* updates translation to Norwegian (nb) (#488 by FTno).
=> release 0.13.9

app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
I didn't find the file where I should add my contribution name, I couldn't find any file named `locale_credits`. 
Before merging, I should add my contribution there.
=> Updated Italian Translation

app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
fix + improvements + (some) missing translation for french language.
=> French big review

CHANGELOG.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/75.txt
* updates translation to Italian (it) (contributed by GiovaGa) (#499).
* updates translation to French (fr) (contributed by ldmpub) (#501).
=> release 0.13.11

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/76.txt
* updates translation to German (de) (#503 by wolkenschieber).
=> release 0.13.12

CHANGELOG.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/79.txt
* updates translation to Norwegian (nb) (#515 by FTno).
* updates translations to Polish (pl) and Esperanto (eo) (#514 by Verdulo).
=> release 0.13.15

README.md, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-eu/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Hi! Here is my translation for your amazing app. I hope I translated everything correctly :)
=> Czech translation - CS

app/src/main/res/values-ca/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-eo/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-eu/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
- creates Simplified Chinese (zh-CN) translation
- completes & fixes Traditional Chinese (zh-TW) translation
=> Chinese translations

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
- Simplified Chinese (zh-CN): completes TODOs, fixes incorrect grammars
- Traditional Chinese (zh-TW):
- completes TODOs, reviews grammars
- replaces vocabularies with Taiwanese usages
=> Chinese translation enhancements

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
- 收集 instead of 蒐集, zh-CN
- symbol/punctuation: CJK comma
=> Chinese translations fixes

app/src/main/AndroidManifest.xml, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmDatabaseAdapter.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java, app/src/main/java/com/forrestguice/suntimeswidget/settings/AppSettings.java, app/src/main/res/values/strings.xml, app/src/main/res/xml-v11/preference_alarms.xml
* adds 'power off alarms' option (#426); untested.
=> power off alarms

app/src/main/res/values-nb/strings.xml
In menu - Sun Position; below the heading there are date and time with Local Mean Time in brackets. Despite being translated Local Mean Time appears in english.
=> Norwegian (nb) translation update

app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml
Late translations to Polish and Esperanto. In descriptions about seasons I omitted the sentences about "northward equinox", etc; such phrases are unused in Polish and Esperanto.
=> updated translations to Polish and Esperanto

app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml
=> updated translations (Polish and Esperanto)

app/src/main/res/values-cs/strings.xml
Hi!
I tried to update TODO translations. I hope I have understood everything correctly.
Thanks for your continuous work on this app.
=> Czech (cs) translations update

app/src/main/res/values-cs/strings.xml
Hi!
As always I translated what was needed.
Have a nice day.
=> Czech (cs) translations update #606

CHANGELOG.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/100.txt
* updates translation to French (fr) (#702 by grenagit). #664
=> release 0.15.3

app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v11/preference_alarms.xml, app/src/main/res/xml/preference_alarms.xml
Very late updates to translations.
I also separated the reused string "Quick notification".
=> update translations (Esperanto + Polish)

app/src/main/res/values-pt-rBR/strings.xml
=> Update pt_BR translation

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> fix: Chinese translation of cross-quarter days

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> feat: updated Chinese translations

app/src/main/java/com/forrestguice/suntimeswidget/calculator/CalculatorProvider.java, app/src/main/java/com/forrestguice/suntimeswidget/calculator/core/CalculatorProviderContract.java
* adds `COLUMN_MOON_RISE_ILLUM`, `COLUMN_MOON_RISE_DISTANCE`, `COLUMN_MOON_SET_ILLUM`, `COLUMN_MOON_SET_DISTANCE`.
* adds `_POSITION_KEYS`; may be combined with `COLUMN_MOON` and `COLUMN_SUN` keys to specify position at time of event.
* bumps provider version 6 (0.5.1) -> 7 (0.6.0)
=> CalculatorProvider

app/src/main/res/values-ru/strings.xml
=> added translations to Russian

CHANGELOG.md, README.md, app/build.gradle, fastlane/metadata/android/en-US/changelogs/111.txt
* adds translation to Arabic (ar) (contributed by Alelg) (#786).
* adds to list of world places, and allows adding world places by continent (#785).
* adds mirror for help urls and website; some locales may point to GitHub hosted resources instead (#629).
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#788 by James Liu).
=> release 0.15.14

CONTRIBUTING.md, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
https://github.com/forrestguice/SuntimesWidget/issues/680 https://github.com/forrestguice/SuntimesWidget/issues/681
=> Chinese translation completions & trimming trailing additional character

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> fix Chinese translations

app/src/main/java/com/forrestguice/suntimeswidget/graph/LightGraphDialog.java, app/src/main/java/com/forrestguice/suntimeswidget/graph/LightGraphExportTask.java, app/src/main/java/com/forrestguice/suntimeswidget/graph/LightGraphView.java, app/src/main/java/com/forrestguice/suntimeswidget/map/WorldMapView.java, app/src/main/java/com/forrestguice/suntimeswidget/themes/WidgetThemePreview.java, app/src/main/java/com/forrestguice/suntimeswidget/views/ShareUtils.java, app/src/main/java/com/forrestguice/suntimeswidget/widgets/layouts/SunPosLayout_3X2_2.java, app/src/main/res/menu/lightgraphmenu.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
* adds "cross-hair" option to sunlight graph.
* adds "share bitmap" action.
* fixes sunlight graph so that it shows jump/skip in time zone dst
=> lightgraph

app/src/main/res/values-eo/strings.xml, app/src/main/res/values-pl/strings.xml
Minor bug: in the window "Sunlight" the vertical axis always show time in 12 hour system instead following user setting.
=> translations to Polish and Esperanto

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> Chinese (zh) translations

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> Chinese Translations updates

app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidgetListActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmAddon.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmEvent.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java, app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmEditActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/events/EventSettings.java, app/src/main/java/com/forrestguice/suntimeswidget/views/ExecutorUtils.java, app/src/main/java/com/forrestguice/suntimeswidget/widgets/WidgetListAdapter.java
* adds a time-out when querying content providers; avoids potential ANRs when a provider fails to return in a timely manner.
=> content provider

app/src/main/java/com/forrestguice/suntimeswidget/graph/LightMapDialog.java, app/src/main/java/com/forrestguice/suntimeswidget/graph/LineGraphView.java
* fixes bug where graph labels are always displayed using 12h time.
* fixes bug where "sun position grid does not re-align when DST changes" (#867).
* adds a warning icon to sun position dialog when the displayed time is adjusted by DST.
=> line graph

app/src/main/res/values-it/strings.xml
Around 300 translated, many more that were already translated are now fixed and coherent. Still ~200 to complete Italian translation
=> translation in Italian

app/src/androidTest/java/com/forrestguice/suntimeswidget/ExceptionActivityTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/com/forrestguice/suntimeswidget/ExceptionActivity.java, app/src/main/java/com/forrestguice/suntimeswidget/ExceptionHandler.java, app/src/main/java/com/forrestguice/suntimeswidget/ExceptionNotification.java, app/src/main/java/com/forrestguice/suntimeswidget/SuntimesApplication.java, app/src/main/res/layout/layout_activity_exception.xml, app/src/main/res/values/strings.xml
* adds custom ExceptionHandler; a notification is shown with the stacktrace if the application crashes.
=> crash report notification
