- CHANGELOG.md
- app/build.gradle
* fixes bug "export places; commas in place names break csv output bug" (#240).
* fixes bug "momentary hang/pause when adding or reconfiguring sunposition widgets (3x1 and 3x2)".
* adds permission explanations to fastlane app description.
* adds runtime permission explanations (a dialog displayed prior to each permission request).
* adds privacy link to about dialog (links to https://github.com/forrestguice/SuntimesWidget/wiki/Privacy); 
* added privacy statement to readme.
* updates translation to Polish and Esperanto (eo, pl) (#238, #241 by Verdulo).
* updates translation to Norwegian (nb) (#236 by FTno).
> prep release 0.9.1

- CHANGELOG.md
- app/build.gradle
* modifies the default colors to improve contrast and readability (#247, #264, #268).
* fixes bug "language selectors fails for some languages" (#262).
* fixes empty widgetlist; an oversized label and icon are now displayed when the list is empty.
* fixes worldmap bug where the sun/moon positions are drawn despite sunlight/moonlight options toggled off.
* fixes settings activity iconography (unique icons for each header); the previous patch only fixed this for older Android versions where the icon attribute is completely ignored.
* updates translation to Basque (eu) (#271 by beriain).
* updates translation to Norwegian (nb) (#270 by FTno).
* updates translation to Polish and Esperanto (eo, pl) (#263, #267 by Verdulo).
> Prep release 0.9.5

- CHANGELOG.md
- app/build.gradle
* fixes bug "sun/moon circles are difficult to see (too small)" (#286) on lightmap and worldmap widgets.
* updates translation to Norwegian (nb) (#285 by FTno).
* updates dependency (Time4A 4.2-2018g).
> prep release 0.10.1

- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/TimeZoneDialog.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesData.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesEquinoxSolsticeData.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesMoonData.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesRiseSetData.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/SuntimesRiseSetData2.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/ca/rmen/sunrisesunset/SunriseSunsetSuntimesCalculator.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/core/SuntimesCalculator.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/sunrisesunset_java/SunriseSunsetSuntimesCalculator.java
- app/src/main/java/com/forrestguice/suntimeswidget/calculator/time4a/Time4ASuntimesCalculator.java
- app/src/main/java/com/forrestguice/suntimeswidget/settings/WidgetTimezones.java
Improves the accuracy of the apparent solar time calculation by using the `equationOfTime` method provided by the calculator (when available; falls back to the default implementation).
related to #154
> equation of time

- CHANGELOG.md
- app/build.gradle
* adds app shortcuts (Android 7.1+); a shortcut to the Widget List, a shortcut to the Theme Editor (#288).
* reveals previously hidden azimuthal map projection in the World Map dialog (#284).
* fixes a CalculatorProvider bug where sun/moon queries returned the wrong data type (Calendar obj vs long timestamp).
> release 0.10.3

- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-pl/strings.xml
- fastlane/metadata/android/eo/full_description.txt
- fastlane/metadata/android/eo/name.txt
- fastlane/metadata/android/pl-PL/full_description.txt
- fastlane/metadata/android/pl-PL/name.txt
I completed the translations (sorry for delay). I also changed Polish name of application to "Czasy Słońca" (exact translation) and added file "name.txt" to metadata.
I have problems with:
alarmAction_timeout (Timeout): this is not button, but title of notification "The alarm timed out.", yes?
What is the difference between configLabel_alarms_silenceAfter (Go silent after) and configLabel_alarms_timeoutAfter (Timeout afte)?
What is difference between "Dismiss" and "Silence" in alarm_hardwarebutton_actions_display?
> translations for Esperanto and Polish

- CHANGELOG.md
- app/build.gradle
* updates translations to Spanish (es-es) and Catalan (ca) (#301 by Raulvo).
* updates translations to Polish (pl) and Esperanto (eo) (#302 by Verdulo).
> release 0.11.1

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/46.txt
* adds support for playing alarm sounds from the file system (mp3, ogg, etc). [Selecting files requires a file manager app with support for ringtone selection.] 
* fixes bug "alarm sound fails to play from external storage" (#326); alarm notifications will fallback to the default ringtone if the selected sound cannot be played.
* new permission: READ_EXTERNAL_STORAGE. This permission is needed to play sounds located on the SD card (#326). [PERMISSION]
* improves language resolution for Spanish locales (#147).
* improves the About Dialog (better translation credits).
> release 0.11.5

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/47.txt
* fixes bug "Suntimes Alarms uses elevation even if unchecked" (#336).
* fixes bug "worldmap dialog fails to apply themed foreground color" (#337).
* fixes bug "unable to dismiss alarm when notifications are disabled" (#333).
* adds a "Notifications" warning to the AlarmClock activity that is shown if notifications are disabled. Notifications are required for alarms to display correctly (#333).
* adds a "Notifications" preference to the Alarm settings. This preference warns when notifications are disabled, or configured to not show on the lock screen (#332, #333).
* adds a "Volumes" preference to the Alarm settings (navigates to system Sound settings).
* optimizes basemaps and preview pngs; size reduced by ~50% using pngquant.
* updates translations to Polish (pl) and Esperanto (eo) …
> release 0.11.6

- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesUtils.java
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-es/strings.xml
Orthographic errors, better terms and date format updates. The latter required to change SuntimesUtils.java source code. The localised date format was read after formatting the string of date + time. Assignment of the variables storing the localised string have been reordered such that the read happens before date+time formatting.
> Spanish & Catalan translations.

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/49.txt
* fixes bug "half hour and 45-minute time zones are listed incorrectly" (#346).
* fixes bug "content provider uses a stale configuration" (#347).
> release 0.11.8

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/52.txt
* enhances the main table to allow scrolling future and past days (#173, #352).
* enhances the moon dialog to allow scrolling future and past months.
* enhances the solstice dialog to allow scrolling future and past years.
* adds moon apogee, perigee, and distance information to the moon dialog (#296).
* adds supermoon and micromoon labels for upcoming new and full moons (#296).
* adds 1x1 moon apogee/perigee widget (#296).
* adds 1x1 moon position widgets; azimuth & elevation, right ascension & declination, or current distance.
* enhances the World Map dialog to animate over time; play/pause or step forward/back to show changes over a span of hours or days (#284).
* adds world map projection "Polar [south]" (#284).
* adds 3x3 sun position widget; Polar [north], Polar [south] map …
> release 0.12.0

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/com/forrestguice/suntimeswidget/getfix/GetFixTask.java
- fastlane/metadata/android/en-US/changelogs/55.txt
* fixes bug "can't get location while gps is working and has a fix" (api17+) (#373).
* improves the accuracy of gps results (applies a simple Kalman filter).
* adds gps "recent max age" values "none" and "any" (ignores gps time when getting fix), and an option to fallback to the last location.
* updates translation to Norwegian (nb) (#374 by FTno).
> release 0.12.3

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/56.txt
* fixes app crash (time zone dialog) (#376).
* fixes potentially long lived AsyncTask to run in parallel with shorter lived tasks (THREAD_POOL_EXECUTOR); "current location" updates no longer block dialogs from loading (#376).
> release 0.12.4

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/57.txt
* adds a "dismiss" button to the reminder notification that allows repeating alarms to be dismissed early (reschedule+1); reveals the reminder notification for api21+ (#387).
* fixes the appearance of ActionModes displayed within BottomSheetDialogFragment.
* fixes bug where ContentProvider would sometimes return uninitialized defaults.
* no longer reschedules alarms in response to TIME_SET broadcast.
> release 0.12.5

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/59.txt
- fastlane/metadata/android/en-US/full_description.txt
* adds "gradually increase volume" option to Suntimes Alarms (#396).
* fixes bug where CalculatorProvider fails to apply the selected time zone (#394).
* updates translation to Brazilian Portuguese (pt-br) (#400 by efraletti).
> release 0.12.7

- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmClockItem.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmDatabaseAdapter.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmClockActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmClockAdapter.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmDismissActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmTimeDialog.java
- app/src/main/res/layout-land/layout_dialog_alarmtime.xml
- app/src/main/res/layout/layout_dialog_alarmtime.xml
Allow for scheduling alarms by solar time (implements #403):
* adds `timezone` field to alarm database (and applies it when scheduling clock time).
* adds time zone spinner to AlarmTimeDialog; limit selection ("System", "Apparent Solar", "Local Mean").
* modifies UI (AlarmClockAdapter, AlarmDismissActivity) to display selected time zone.
> solar alarm

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/60.txt
* adds ability to set an alarm in solar time (#403); adds `timezone` field to alarm item database; increments database version (`1` -> `2`).
* adds field to CalculatorProvider; `COLUMN_CONFIG_APP_THEME_OVERRIDE`; increments CalculatorProvider versionCode (`3` -> `4`).
* adds a ContentProvider (SuntimesThemeProvider) that provides access to user-defined themes.
* exports the ThemeList activity; permits access to third-party apps with the `suntimes.permission.READ_CALCULATOR` permission.
* fixes bug where NotificationService continues running after scheduling a notification or distant alarm.
> release 0.12.8

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/63.txt
* fixes bug "sun position widget does not render midnight sun" (fix #421).
* fixes app crash when using fallback to "last location" (fix #420).
> release 0.12.11

- app/src/androidTest/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivityTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesWidgetListActivity.java
* enhances the WidgetListActivity to show add-on widgets (and allow reconfigure).
* replaces implicit update intent with a series of explicit intents (one for each widget receiver).
* [permission] adds `uses "suntimes.permission.READ_CALCULATOR"` to main app (previously only declared by main app and used by addons); needed to secure addon contentproviders
> widgetlist

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/66.txt
* adds support for overriding location when creating alarms via Intent.
* adds a hex color field to the rgb color picker.
* fixes bug where ColorDialog sliders sometimes start with the wrong value.
* fixes crash in AlarmClockActivity when notifications are disabled (fixes #437).
* fixes bug "incorrect future and past number of days, when DST starts or ends" (fixes #436).
* fixes spannable icons (too small / unreadable) to be consistent across devices.
* improves organization of "User Interface" settings (#434).
* exports the WidgetListActivity, ActionListActivity, and SettingsActivity; permits access to third-party apps with the `suntimes.permission.READ_CALCULATOR` permission.
* enhances the WidgetListActivity to show add-on widgets (and allow reconfigure).
* **[permission]** The app now …
> release 0.13.2

- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru-rUA/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- fastlane/metadata/android/ru/full_description.txt
- fastlane/metadata/android/ru/short_description.txt
Full Russian translation. Based on the original file (follows instructions from CONTRIBUTING.md).
Contains a few TODOs for future work.
> Russian translation

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/70.txt
* adds support for sidereal time (GMST, LMST) (closes #463).
* adds "alarm list" button to the alarm dialog (closes #455); shortcut to Suntimes Alarms.
* adds "SHOW_CARD" action to main activity; allows other apps to scroll to a given date.
* fixes widget click action so that it also triggers an update (fixes #459).
* misc time zone dialog improvements.
> release 0.13.6

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/71.txt
* fixes bug "alarm vibration stops after screen is off" (closes #470).
* fixes broken build caused by failing `colorpicker` dependency.
* updates translation to Polish and Esperanto (eo, pl) (#468 by Verdulo).
> release 0.13.7

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/74.txt
* adds 'import places'; import from a previously exported csv (#419).
* changes moon illumination message; "% illuminated" to "% @ <lunarNoon>" (#384).
* miscellaneous theme fixes and improvements (#492):
* app now applies theme text sizes.
* app now hides default widget themes from list (recommended for widgets only).
* app now shows a warning when the theme is changed; "app restart may be needed for changes to take effect".
* theme editor now allows choosing fractional sp values.
* theme editor now changes previews when map/graph colors are modified.
* fixes bug "current location title not translated" (closes #467).
* updates translation to Polish and Esperanto (eo, pl) (#491 by Verdulo).
> release 0.13.10

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/77.txt
* fixes bug "1x1 moon widget uses imperial units while the app metric" (closes #506).
> release 0.13.13

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/81.txt
* adds translation to Simplified Chinese (zh_CN) (contributed by James Liu) (#527).
* updates translation to Traditional Chinese (zh_TW) (#527).
* fixes alarm notifications to include the 'offset' text (more descriptive); e.g. "5m before sunset" vs "sunset" (#522).
* fixes crash when loading AlarmCreateDialog with invalid settings (handle unknown event values).
> release 0.13.17

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/83.txt
* adds help for `data source` setting; adds link to online help (closes #223).
* reorganizes General settings (#533); `show seconds` restored to `general`; `data source` moved into `advanced`; hides `experimental`. 
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#543 by James Liu).
* updates translation to Norwegian (nb) (#542 by FTno).
> release 0.13.19

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/85.txt
* fixes crash when using "current location" (fixes #556).
* fixes bug "lightmap for tomorrow card fails to display" (fixes #557).
* fixes bug "content-provider supplies the wrong time zone" (fixes #554).
* adds default world places; ~34 additional locations.    
* adds 'online-help' link to actions help dialog (#489, closes #546).
* changes default 'solar time' mode to Local Mean Time.
* minor fixes to `en` translations; e.g. `en_US` and `en_CA` display 'fall equinox'.
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#553 by James Liu).
* updates translation to Norwegian (nb) (#561 by FTno).
> release 0.14.1

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/86.txt
* fixes crash when using 'sun position' app shortcut (closes #567).
* fixes bug where "search places doesn't work" (closes #566).
* fixes bug where '1x1 moon widget' illumination is always displayed (fails to be hidden) (closes #563).
* changes default 'time zone mode' back to `system`; reverts change from 7c288be (closes #565).
* adds extras to SuntimesActivity intent; `ACTION_VIEW_SUN` and `ACTION_VIEW_WORLDMAP` now accept `EXTRA_SHOW_DATE`; `ACTION_ADD_ALARM` accepts `EXTRA_SOLAREVENT`.
* updates translation to Norwegian (nb) (#568 by FTno).
* updates translations to Polish (pl) and Esperanto (eo) (#571 by Verdulo).
> release 0.14.2

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/87.txt
* adds click to solar noon field; opens the lightmap dialog (closes #562).
* changes click on sunrise/sunset headers; opens the lightmap dialog if configured to show azimuth (closes #562).
* fixes lunar noon field; omit on days it doesn't occur (#572).
* fixes bug "solstice dialog 'view date' menu doesn't work" (closes #577).
* fixes bug where the AlarmNotifications service fails to stop (battery use in background) (closes #575).
* fixes ANR when showing alarm dialog (closes #576); misc changes to ringtone management.
* fixes app crash when using 'fallback to last location'.
* fixes bug where changes made in the PlacesActivity aren't displayed by the location spinner.
* changes action prefix to "suntimes.action"; remaps legacy actions.
* misc layout changes (enlarged click areas); misc …
> release 0.14.3

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/88.txt
* adds import/export to SuntimesAlarms (closes #588); save and load alarms/notifications as JSON.
* adds widget layouts (3x1 sun position); show the lightmap graph with reduced height (#589).
* extends map widgets to use the dialog configuration; shared options for center/background/tint, sunlight/moonlight, location, latitudes, and graticule (#493).
* extends the widget action dialog to suggest package and class names from installed apps (#546).
* fixes bug where widget actions that use an explicit intent fail to launch (closes #546).
* fixes bug where widget action extras are not correctly applied (#546); ints omitted, longs applied as String.
* fixes bug where the sun position and map animations runs in the background (closes #582).
* fixes bug in sun position widget where the theme …
> release 0.14.4

- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/AlarmDatabaseAdapterTest.java
- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettingsTest.java
- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/ImportAlarmsTest.java
- app/src/androidTest/java/com/forrestguice/suntimeswidget/settings/AppSettingsTest.java
- app/src/main/java/com/forrestguice/suntimeswidget/ExportTask.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmClockItemExportTask.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmClockItemImportTask.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmListDialog.java
- app/src/main/java/com/forrestguice/suntimeswidget/getfix/ExportPlacesTask.java
- app/src/main/java/com/forrestguice/suntimeswidget/getfix/PlacesListFragment.java
- app/src/main/java/com/forrestguice/suntimeswidget/settings/AppSettings.java
- app/src/main/java/com/forrestguice/suntimeswidget/themes/ExportThemesTask.java
- app/src/main/java/com/forrestguice/suntimeswidget/themes/WidgetThemeListActivity.java
- app/src/main/res/layout/layout_dialog_alert.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml-v11/preference_alarms.xml
- app/src/main/res/xml/preference_alarms.xml
* fixes bug where alarm import is unable to select previously exported files (#588).
* adds export file selection (alarms/places/themes) using Storage Access Framework (api19+) (older devices still use `ACTION_SEND`) (#588).
* adds import warning dialog; alarm sounds and actions may revert to defaults (#588).
> alarm export

- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/AlarmDatabaseAdapterTest.java
- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotificationsTest.java
- app/src/androidTest/java/com/forrestguice/suntimeswidget/alarmclock/ImportAlarmsTest.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmClockItem.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmDatabaseAdapter.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java
- app/src/main/res/raw/alarmsound.rtttl
- app/src/main/res/raw/notifysound.rtttl
- app/src/main/res/values/strings.xml
* fixes bug "default alarm sound fails to play" (#593).
* fixes bug "sounding/snoozing notification is unexpectedly canceled" (#594).
> alarm service

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/90.txt
* fixes crash when changing an alarm's time/event (closes #605).
* fixes bug where despite setting units to metric the altitude is displayed in feet (closes #604); [Android Go]
* updates translation to Czech (cs) (#606 by utaxiu).
> release 0.14.6

- CHANGELOG.md
- app/build.gradle
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java
- fastlane/metadata/android/en-US/changelogs/93.txt
* adds "update all" to widget actions (#625).
* fixes app crash when the default alarm ringtone is unavailable (fixes #633).
* fixes wrong/missing colors when using system dark mode.
* fixes "size of sun in 2x1 and 3x1 lightmap widgets" (fixes #624).
* fixes lightmap "long click" to be consistent with a normal click.
* fixes alarm notification "dismiss" label to help improve context (#628).
* updates translation to Norwegian (nb) (#632 by FTno).
* updates translation to German (de) (#631 by CSTRSK).
* updates translation to Czech (cs) (#630 by utaxiu).
> release 0.14.9

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/94.txt
* adds "abbreviated month names" widget option (#625).
* adds a help dialog to the alarm edit activity (#628); adds "day light saving" to main help dialog.
* fixes bug "alarms do not compensate for time zone changes" (fixes #643).
* fixes bug "BOOT_COMPLETED fails to reschedule stale alarms" (fixes #641).
* fixes bug where the "light theme" is only partially applied (when system dark mode is also enabled).
* fixes 3x1 sun position widget "scale text and icons" option; changes labels to bold for better readability (#625).
> release 0.14.10

- .github/workflows/android.yml
- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmClockActivity.java
* adds permission `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`
This permission is added for overall better UX, making it is significantly easier for users to whitelist the app (required for reliable alarms). Suntimes is a clock app and alarms are one of its core functionalities, so [use of this permission is justified](https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases).
> request ignore battery optimizations [permission]

- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmClockActivity.java
- app/src/main/res/values/strings.xml
* adds a help dialog that explains battery optimization warnings and links to online help.
* shows a revised warning message for devices that are likely to break alarms.
* the app now makes a direct request to ignore battery optimizations (if `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` is granted).
> alarms battery optimization warning

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/forrestguice/suntimeswidget/SuntimesSettingsActivity.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmSettings.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/ui/AlarmClockActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml-v11/preference_alarms.xml
- app/src/main/res/xml/preference_alarms.xml
* SuntimesAlarms activity now reschedules all alarms if `boot_completed` has failed to run.
* AlarmNotificationService now reschedules all alarms after app upgrades (`android.intent.action.ACTION_MY_PACKAGE_REPLACED` broadcast).
* adds a foreground service notification while rescheduling all alarms (shown during `boot_completed`, and `timezone_changed`).
* adds "Boot Completed" to the Alarm Settings; shows reboot information and manually triggers "reschedule all".
* AlarmNotificationService `onScheduled_*` events now broadcast `update_ui` (forces running apps to update their UI).
> alarms reboot

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/95.txt
* adds permission REQUEST_IGNORE_BATTERY_OPTIMIZATIONS (#651) [PERMISSION]; SuntimesAlarms now makes a direct request to be added to the whitelist.
* adds a help dialog that explains battery optimization warnings; adds online help; a revised message is shown for devices that are likely to break alarms.
* adds data substitutions `eot` (formatted equation of time), and `eot_m` (equation of time millis) (#649).
* adds "Boot Completed" to the Alarm Settings; shows reboot information and manually triggers "reschedule all" (#653).
* adds a foreground service notification that is shown while rescheduling all alarms (#653).
* changes SuntimesAlarms to reschedule all alarms after an app upgrade (ACTION_MY_PACKAGE_REPLACED), or if it detects that boot_completed has failed to run.
* adds …
> release v0.14.11

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/96.txt
* adds a boot "warning notification" if battery optimization is enabled (and alarms are active).
* fixes bug "dismissing alarm fails to remove alarm notification" (closes #665).
* fixes bug when re-scheduling repeating moon phase alarms (#494; "unreliable full moon alarm").
* fixes bug where toast messages are unreadable when using system dark mode (white text on a white background) (Android 12) (closes #660).
* fixes bug in AlarmEditActivity where the UI fails to display the configured label.
* fixes bug "alarm reminder is not shown after changing 'reminder within' setting" (closes #659).
* fixes potential NPE in AlarmNotifications `updateAlarmTime_` methods when repeatingDays is null.
* fixes potential NPE in AlarmEditActivity when alarm location is null.
* fixes potential NPE in …
> release 0.14.12

- CHANGELOG.md
- README.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/98.txt
* adds themed icon (Android 13+).
* adds Chinese, Indian, Japanese, Korean, Minguo, and Vietnamese calendars to the date widget (closes #692).
* adds %eZ@ (azimuth), %eD@ (declination), and %eR@ (right ascension) title substitutions (#677).
* fixes bug "app crash when showing moon dialog from shortcut" (closes #691).
* fixes bug "widgets crash with lawnchair2" (closes #689, closes #690).
* fixes bug "navigation bar is white instead of black with dark theme" (closes #696).
* fixes bug where the main table header displays azimuth at civil twilight instead of sunrise/sunset.
* fixes bug where scaled text is cropped in 1x1 moon widget and 1x1 date widget.
* updates translation to Norwegian (nb) (#693 by FTno).
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese …
> release 0.15.1

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/99.txt
* adds themed alarms icon (Android 13+); updates shortcut icons (adaptive).
* adds "quick notification" alarm shortcut; adds "world map" app shortcut; removes "themes" shortcut.
* adds a warning message when overriding the locale; "the app may need to be restarted before changes take full effect".
* fixes bug where overriding the locale is not immediately applied to existing widgets.
* fixes bug where changes to settings from the WelcomeActivity are not applied until after the app is restarted.
* fixes bug "sun position doesn't update on main screen" (closes #695).
* fixes bug "broken 2x1 sun widget preview".
* misc refactoring (reorganizes WidgetLayout and SettingsActivity classes).
* fixes spelling error in translation to German (de) (#698 by Das-Nichts).
* updates translations to …
> release 0.15.2

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/102.txt
* adds Hijri calendar to the date widget (closes #714).
* fixes bug where alarms using Apparent Solar Time drift over time (closes #715).
* fixes bug where app dialogs display Apparent Solar Time with reduced accuracy.
* fixes bug where actions fail to apply all available %substitutions.
* fixes bug where actions fail to apply the correct `extra type` to %substitutions.
* increases max snooze from 59 to 120 minutes; increases max "auto dismiss" from 59 to 300 seconds.
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#716 by James Liu).
> release 0.15.5

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/103.txt
* improves time zone defaults (localized default values).
* improves time zone recommendations; fixes recommendation when place names contain spaces or special characters.
* adds "recommend time zone" action to time zone dialog.
* fixes time zone list to show the correct display name and offset when day light saving is applied.
* fixes app crash when addons attempt to open settings with an invalid fragment.
* changes labels for cross-quarter days (#719); Imbolc, Beltane, Lughnasadh, Samhain.
* updates translation to Polish and Esperanto (eo, pl) (#722 by Verdulo).
* updates translation to Brazilian Portuguese (pt-br) (#721 by naoliv).
> release 0.15.6

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/104.txt
* adds a warning to SuntimesAlarms when the "Autostart" setting is disabled (Xiomi devices only) (closes #730).
* fixes bug "time refreshes aren't happening properly" (closes #705).
* fixes bug where the update loop continues running in the background after the activity is no longer visible.
* fixes bugs where rapidly clicking triggers actions more than once (throttled click listeners).
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#728 by James Liu).
> release 0.15.7

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/105.txt
* adds a warning when the app is configured to "current location" but location permissions are denied (#733).
* changes the location label when switching away from "current location" mode (#733).
* fixes a bug in "current location" mode; the location automatically refreshes when the activity is resumed (closes #733).
* fixes a bug where the time zone selector shows the wrong system time zone (closes #733).
* fixes a bug where the alarm event icon and text are out of alignment.
* refactors alarm adapter click listeners (bind rowID instead of position).
* updates translation to Hungarian (hu) (#736 by titanicbobo) (#670).
> release 0.15.8

- CHANGELOG.md
- README.md
- app/build.gradle
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
- fastlane/metadata/android/en-US/changelogs/107.txt
* adds layouts and resources for very small screens (#727); experimental support for wearables.
* adds 'columns' setting to moon dialog; 2, 3 or 4 columns.
* fixes bug "can't interact with app after install (flashes/strobes)" (closes #760).
* fixes bug "custom date format is not saved"; adds calendar format pattern "EE, MMM d" (closes #759).
* fixes app crash when tapping on the date (closes #751).
* fixes bug where the solstice widget displays "cross-quarter days" when disabled by the app (#755).
* fixes bug where moon dialog content is clipped (#754).
* increments `CalculatorProviderContract` version 5 -> 6; fixes columns for "cross-quarter days".
* changes "header labels" default to "none" for translations with longer strings (de, fr, hu, nb, nl, pt_BR) (#754).
* miscellaneous updates …
> release 0.15.10

- CHANGELOG.md
- README.md
- app/build.gradle
- app/src/main/res/values/strings.xml
- fastlane/metadata/android/en-US/changelogs/109.txt
* increases the range of supported dates from +-2.5 years to +-500 years (#770).
* fixes bug where date selector allows selecting unsupported dates (closes #770), and other miscellaneous UI changes.
* fixes bug where alarm screen back button overlaps the dismiss button (closes #777).
* fixes bug in date widget where the scaled text is not centered (closes #763).
* fixes ambiguity in minutes abbreviation; replaces "m" with "min" for all translations that default to metric (#773).
* updates translation to Russian (ru) (#775 by Adelechka).
> release 0.15.12

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/110.txt
* adds app options to show daylight comparison (today/tomorrow) (closes #773).
* increases the maximum before/after alarm offset (closes #779); fixes localization of display values.
* fixes app crash when launching the app after using "restore backup" (closes #783).
* replaces links to "online help" and improves help presentation; the app's website is now hosted on Codeberg (https://forrestguice.codeberg.page/Suntimes/) (#629).
* now mirroring git repository to Codeberg (https://codeberg.org/forrestguice/Suntimes) (#629).
> release 0.15.13

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
> Add Arabic translation

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/112.txt
* adds online user manual; https://forrestguice.github.io/Suntimes/help/ or https://forrestguice.codeberg.page/Suntimes/help/
* fixes app crash when using custom themes (closes #792).
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#791 by James Liu).
* updates translation to Polish and Esperanto (eo, pl) (#793 by Verdulo).
> release 0.15.15

- app/src/main/res/values-nb/strings.xml
> Norwegian (nb) translation update

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/113.txt
* adds "online help" links to existing help dialogs (closes #797).
* fixes bug where "moon phase alarm time is incorrect" (closes #803).
* fixes bugs when using d-pad navigation within dialogs (Android TV).
* updates translation to Norwegian (nb) (#796, #801 by FTno). #674 
* updates translations to Simplified Chinese (zh_CN) and Traditional Chinese (zh_TW) (#799, #800 by James Liu). #680 #681
> release 0.15.16

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/114.txt
* adds "sidebar navigation", and an option to change the "launcher activity" (closes #505).
* adds support for custom events based on "shadow length" (closes #331).
* adds support for customizing the app color scheme; override map, graph, and highlight colors.
* adds "light graph" dialog (of sunlight over the year) (closes #735), "earliest/latest sunrise/sunset" info (closes #753), and a 3x2 graph widget (to sun position widgets).
* adds "use app location" option to alarms; reschedules alarms automatically when the location is changed (closes #768, closes #808).
* adds "bedtime mode" to alarms; helps schedule do-not-disturb during sleep hours (closes #425).
* adds "high brightness" option (closes #741) and swipeable buttons (closes #738) to the alarm screen.
* adds "next alarm" quick …
> release 0.16.0

- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
> Chinese translation

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/115.txt
* adds "material colors" (palette) to color dialog.
* adds text color preview, and other miscellaneous color picker improvements.
* adds "cross-hair" option to sunlight graph; adds "share bitmap" action.
* fixes sunlight graph so that it shows jump/skip in time zone dst (closes #735).
* fixes inconsistent text/point sizes between graph views.
* fixes bug where the lightmap widget is rendered incorrectly (closes #812).
* fixes bug where "sunlight dialog axis labels don't follow user settings (always 12 hour time)". (#824)
* enhances Alarm Settings warnings; show a warning when alarm notifications are disabled on the lock screen (closes #332).
* enhances Alarm Settings warnings; show warnings when alarm channel is muted, or notifications are temporarily paused/suspended.
* fixes broken …
> release 0.16.1

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/116.txt
* adds "bright alarm colors"; allows customization of fullscreen alarm colors (#741).
* adds "do-not-disturb" preference that indicates the state of the required permission (#818).
* adds "app restricted" warning; "Alarms may fail to work reliably" when the app is in the rare or restricted app-standby-bucket.
* fixes crash in sunlight widget (#735).
* fixes missing "bright alarm" setting (Android 14) (#741).
* fixes bug where bedtime do-not-disturb fails to activate (#818).
* fixes bug where bedtime notifications are hidden due to low priority (adds a separate bedtime notification channel).
* fixes bug where the alarm foreground service fails to stop after triggering notifications.
* fixes missing notification text when the alarm foreground service does periodic work.
* fixes text …
> release 0.16.2

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/117.txt
* enhances the quick settings tiles to support displaying their dialogs over the lock screen.
* improves the appearance of the quick settings tile dialogs (replaces AlertDialog).
* fixes app crash when configuring quick settings tiles.
* fixes bug where quick settings tiles use the wrong default values.
* adds a "restore defaults" action to the widget configuration activity.
* enhances "bedtime mode" to support Direct Boot; responds to `LOCKED_BOOT_COMPLETED` to restore bedtime state after a reboot.
* adds "DND rules" option to "bedtime mode"; this advanced option allows choosing between using automatic DND rules, or overriding DND directly (#818).
* fixes the bedtime notification tap action; tapping the notification opens the bedtime activity.
* revises the notification text displayed …
> Release 0.16.3

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmJobService.java
- app/src/main/java/com/forrestguice/suntimeswidget/alarmclock/AlarmNotifications.java
* fixes bug "FGS not allowed to start from BOOT_COMPLETED!" (Android 15).
* adds action `AFTER_BOOT_COMPLETED`; changes `ACTION_BOOT_COMPLETED` so that it defers scheduling alarms until a moment later (https://github.com/forrestguice/SuntimesWidget/issues/842)
* removes duplicate progress notification when re-scheduling alarms.
> boot completed

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/118.txt
* fixes bug "boot completed hangs after phone restart" (closes #842).
* fixes bug "FGS not allowed to start from BOOT_COMPLETED!" (Android 15).
* fixes bug where "moon dialog displays the wrong phase label" (closes #843).
* fixes bug where custom color labels are invisible when ellipsized (missing text).
* fixes bug where text is cropped in moon day widget (closes #845).
* fixes bugs in widget previews; missing padding, missing map foreground.
* adds "preview" action to the "bright alarm colors" selector.
* adds `AFTER_BOOT_COMPLETED`; changes `ACTION_BOOT_COMPLETED` so that it defers scheduling alarms until a few moments later (#842, #853).
* adds time-out when querying various content providers to avoid potential ANRs if a provider fails to respond (#852).
* updates build; replaces …
> release 0.16.4

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/120.txt
* adds option for "solar midnight" (closes #835).
* adds world places: ~110 places; North American capitols, major US cities, and others.
* increases maximum "auto-dismiss after" notification value from 5 minutes to 12 hours (#726).
* improves UI when configuring time offsets for custom events, alarm, and bedtime settings.
* fixes bug where "sun position grid does not re-align when DST changes" (closes #867).
* enhances `%e` data patterns to work with all widget types (no longer limited to sun widgets).
* adds data patterns: `%es`, `%eS`, `%h`, and `%H`; shadow length, and observer height.
* adds data patterns: `%ea`, `%ez`, `%ed`, and `%er`; altitude, azimuth, declination, right-ascension.
> release 0.16.6

- CHANGELOG.md
- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/124.txt
* adds a crash report notification that displays the stacktrace when the application crashes.
* adds "Boot Completed (Delay)" to alarm settings; adds intentional delay when rescheduling alarms after reboot.
* fixes "app crash after phone restart" (closes #894).
* fixes "app crash in the Sun Dialog when rotating the device".
* fixes bug where custom event alarm times are truncated to the minute.
* fixes bug where content provider fails to schedule custom events on past days.
* increments `CalculatorProviderContract` version 8 -> 9; adds support for custom events to the `sun` query (projections may include custom event ids).
* increments `AlarmEventContract` version 1 -> 2; eventInfo can now be queried by type with selectionArgs.
* updates translation to Italian (it) (#893 by McCio). #675
> release 0.16.10
